{# templates/bundles/TwigBundle/Exception/error404.html.twig #}
{# pour test : https://localhost:8000/_error/ #}
{% extends 'base.html.twig' %}

{% block body %}

 <div id="layoutError">
            <div id="layoutError_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <div class="text-center mt-5 py-4">
                                    <h1 class="display-1">Error</h1>
                                    <p> La requête n'a pas pu être traitée, merci de vérifier l'URL ou de revenir à la page d'accueil.</p>
                                    <a href="{{ path('homepage') }}">
                                        <i class="fas fa-arrow-left me-1"></i>
                                        Retour à la page d'accueil
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
<div id="layoutError_footer">

{% endblock %}

