{# templates/bundles/TwigBundle/Exception/error404.html.twig #}
{# pour test : https://localhost:8000/_error/500 #}
{% extends 'base.html.twig' %}

{% block body %}
    <div id="layoutError">
            <div id="layoutError_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <div class="text-center mt-5 py-4">
                                    <h1 class="display-1">500</h1>
                                    <p class="lead">Erreur interne du serveur</p>
                                    <a href="{{ path('homepage') }}">
                                        <i class="fa fa-arrow-left me-1"></i>
                                        Retour Ã  la page d'accueil
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
<div id="layoutError_footer">

{% endblock %}
